---
name: Lint pull request

on:
  pull_request:
    branches: [master, main]

jobs:

  lint_tf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Check tf format
        run: |
          # checking tf format if there are tf files
          set -o nounset   # fail if var undefined
          set -o noclobber # don't overwrite exists files via >
          set -o pipefail  # fails if pipes (|) fails
          set -o errexit   # exit on error

          FILES=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.(tf|tfvars)$' | xargs)

          if [[ $FILES ]]; then
            DIRS=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -E '\.(tf|tfvars)$' | xargs dirname | uniq | xargs)
            exit_code=0
            for DIR in $DIRS; do
              echo "Checking $DIR"
              terraform fmt -list=true -recursive -check -no-color $DIR
              exit_code=$?
              if [ $exit_code -ne 0 ]; then
                exit_code=1
              fi
              exit $exit_code
            done
          else
            echo "Nothing to check"
          fi
        shell: bash {0}
